const travelAndLifestyle = [
  'active vacation',
  'city & cultural travel',
  'family travel',
  'single vacation',
  'party trip',
  'backpacking',
  'adventure travel',
  'beach',
  'business travel',
  'clubbing',
  'couple vacation',
  'cruising (maritime)',
  'cultural travel',
  'honeymoon',
  'language',
  'lifestyle travel',
  'luxury travel',
  'recreational travel',
  'river cruise',
  'road trip',
  'safari',
  'sight-seeing',
  'study travels',
  'sun-bathing'
];

const nightlifeAndSocializing = [
  'restaurant & bistro',
  'bar & lounge',
  'club & dance',
  'casino',
  'comedy',
  'karaoke',
  'cinema',
  'circus',
  'festival',
  'go clubbing',
  'gala'
];

const musicAndEvents = [
  'pop & rock',
  'classic',
  'jazz & blues',
  'hard & heavy',
  'electronic & dance',
  'folk',
  'club-concerts',
  'festival',
  'hip hop & r´n´b'
];

const sportsAndFitness = [
  'soccer',
  'tennis',
  'running',
  'cycling',
  'motorsports',
  'athletics',
  'golf',
  'aerobics',
  'aikido',
  'airsoft',
  'american football',
  'archery',
  'athletics',
  'auto racing',
  'badminton',
  'base jumping',
  'baseball',
  'basketball',
  'beach soccer',
  'beach volleyball',
  'biathlon',
  'billiards',
  'bmx',
  'boating',
  'bobsledding',
  'bodybuilding',
  'bodysurfing',
  'bootcamp',
  'bouldering',
  'bowling',
  'boxing',
  'bull riding',
  'bungee jumping',
  'camping',
  'canoeing',
  'cardio',
  'cheerleading',
  'climbing',
  'cricket',
  'croquet',
  'cross-country skiing',
  'cross-skating',
  'crossfit',
  'curling',
  'dancing',
  'darts',
  'discus throwing',
  'diving',
  'dodgeball',
  'dog sledding',
  'equestrian sports',
  'fencing',
  'field hockey',
  'figure skating',
  'fishing',
  'frisbee',
  'gliding',
  'go karting',
  'gymnastics',
  'hammer throw',
  'handball',
  'heli skiing',
  'hiit',
  'hiking',
  'hockey',
  'horse jumping',
  'horse polo',
  'horse racing',
  'horseback riding',
  'hunting',
  'hurdles',
  'ice hockey',
  'ice skating',
  'inline hockey',
  'inline skating',
  'jet skiing',
  'jogging',
  'judo',
  'jujitsu',
  'karate',
  'kayaking',
  'kendo',
  'kick boxing',
  'kite surfing',
  'kung fu',
  'lacrosse',
  'long jump',
  'luge',
  'marathon',
  'martial-arts',
  'miniature golf',
  'mixed martial arts',
  'modern pentathlon',
  'moto gp',
  'motocross',
  'motorcycle racing',
  'motorcycling',
  'mountain biking',
  'mountaneering',
  'muay thai',
  'nascar',
  'nordic walking',
  'paddleboarding / standup paddling',
  'paddling',
  'paintball',
  'parachuting / skydiving',
  'paragliding',
  'parasailing',
  'parkour',
  'pentathlon',
  'personal training',
  'pilates',
  'pole vaulting',
  'quad',
  'quidditch',
  'rafting',
  'rock climbing',
  'rodeo',
  'roller hockey',
  'roller skating',
  'rollerblading',
  'rowing',
  'rugby',
  'sailing',
  'scuba diving',
  'shooting',
  'shuffleboard',
  'skateboarding',
  'skating',
  'skiing',
  'snooker',
  'snorkeling',
  'snowboarding',
  'snowmobiling',
  'snowshoeing',
  'softball',
  'spinning',
  'squash',
  'sumo wrestling',
  'surfing',
  'swimming',
  'synchronized swimming',
  'table tennis',
  'taekwondo',
  'tag rugby',
  'tai chi',
  'trampoline',
  'triathlon',
  'unicycling',
  'volleyball',
  'wakeboarding',
  'walking',
  'water aerobics',
  'water polo',
  'water skiing',
  'weightlifting',
  'wheelchair sports',
  'windsurfing',
  'wrestling',
  'wushu',
  'yoga',
  'zirkel workout'
];

const cultureAndArt = [
  'cinema',
  'museum & exhibition',
  'theatre & cabaret',
  'arts & crafts',
  'film & music',
  'literature & journalism',
  'animation',
  'architecture & construction',
  'ballet',
  'board games',
  'body art',
  'book club',
  'comics',
  'communication',
  'composition',
  'computer games',
  'craftwork',
  'dance',
  'design',
  'education',
  'exhibitions',
  'film',
  'graphics',
  'handcraft',
  'journalism',
  'library',
  'literary studies',
  'media studies',
  'musical',
  'opera & operetta',
  'painting',
  'photography',
  'printing',
  'radio broadcasting',
  'science-fiction',
  'sculpting',
  'show',
  'theatre',
  'tv',
  'world literature'
];

const interests = [
  ...travelAndLifestyle,
  ...nightlifeAndSocializing,
  ...musicAndEvents,
  ...sportsAndFitness,
  ...cultureAndArt
];

module.exports = interests;
