const architectureAndEngineering = [
  'aerospace engineer',
  'aerospace engineering and operation technician',
  'agricultural engineer',
  'architect',
  'architectural drafter',
  'biomedical engineer',
  'chemical engineer',
  'civil engineer',
  'civil engineering technician',
  'computer hardware engineer',
  'electrical and electronics drafter',
  'electrical and electronics engineer',
  'electrical and electronics engineering technician',
  'electro-mechanical technician',
  'environmental engineer',
  'environmental engineering technician',
  'industrial engineer',
  'marine engineer',
  'materials engineer',
  'mechanical drafter',
  'mechanical engineer',
  'mechanical engineering technician',
  'mining and geological engineer',
  'nuclear engineer',
  'petroleum engineer',
  'surveying and mapping technician',
  'surveyor, cartographer or photogrammetrist'
];

const artsDesignEntertainmentSportAndMedia = [
  'actor',
  'announcer',
  'artists and related worker',
  'athletes, coaches, umpires and related worker',
  'audio and video equipment technician',
  'broadcast technician',
  'camera operator',
  'choreographer',
  'dancer',
  'designer',
  'entertainers and performer',
  'film and video editor',
  'lecturer',
  'media and communication worker',
  'musicians, singers and related worker',
  'news analysts, reporters and correspondent',
  'photographer',
  'producers and director',
  'public relations specialist',
  'sound engineering technician',
  'writers and editor',
  'mechanical engineering technician',
  'mining and geological engineer',
  'nuclear engineer',
  'petroleum engineer',
  'surveying and mapping technician',
  'surveyor, cartographer or photogrammetrist'
];

const buildingGroundsCleaningAndMaintenance = [
  'cleaner',
  'groundskeeper',
  'janitor ',
  'landscaping and grounds keeping worker',
  'maid and housekeeping',
  'pest control worker',
  'supervisor of housekeeping and janitorial work',
  'supervisor of landscaping, lawn-service and grounds keeping',
  '(chimney) sweep',
  'tree trimmer and pruner'
];

const businessAndFinancialOperations = [
  'accountant',
  'agent and business manager of artists, performers and athletes',
  'appraiser and assessor of real estate',
  'auditor',
  'bank director',
  'budget analyst',
  'buyer and purchasing agent',
  'claim adjuster, examiner and investigator',
  'compensation, benefits and job analysts specialist',
  'compliance officer',
  'corporate development director',
  'cost estimator',
  'credit analyst',
  'credit counselor',
  'financial analyst',
  'financial examiner',
  'fundraiser',
  'human resources specialist',
  'insurance appraiser',
  'insurance underwriter',
  'labor relations specialist',
  'loan officer',
  'logistician',
  'management analyst',
  'market research analyst',
  'marketing specialist',
  'meeting, convention and event planner',
  'personal financial advisor',
  'revenue agent',
  'tax examiner and collector',
  'tax preparer',
  'training and development specialist'
];

const communityAndSocialService = [
  'behavioral disorder counselor',
  'child, family and school social worker',
  'clergy',
  'community health worker',
  'educational, guidance, school and vocational counselor',
  'health educator',
  'healthcare social worker',
  'marriage and family therapists',
  'mental health and substance abuse social worker',
  'mental health counselor',
  'probation officer',
  'rehabilitation counselor',
  'religious worker',
  'social and human service assistant',
  'substance abuse counselor'
];

const computerAndMathematicalOperations = [
  'actuary',
  'computer and information research scientist',
  'computer network architect',
  'computer network support specialist',
  'computer programmer',
  'computer systems analyst',
  'computer user support specialist',
  'database administrator',
  'information security analyst',
  'mathematical technician',
  'mathematician',
  'network and computer systems administrator',
  'operation research analyst',
  'software developer',
  'statistician',
  'web developer'
];

const constructionAndExtractionOperations = [
  'brick mason',
  'carpenter',
  'carpet, floor and tile installer',
  'cement mason and concrete finisher',
  'construction and building inspector',
  'construction laborer',
  'derrick, rotary drill and service unit operator, oil, gas and mining',
  'drywall installer',
  'earth drillers',
  'electrician',
  'elevator installation and maintenance',
  'explosives workers',
  'glazier',
  'hazardous material removal worker',
  'helper, construction trade',
  'highway maintenance worker',
  'insulation worker',
  'mining machine operator',
  'operating engineer',
  'painter',
  'paperhanger',
  'paving, surfacing and tamping equipment operator',
  'pile-driver operator',
  'pipe layer',
  'plasterer and stucco mason',
  'plumber, pipe- and steamfitter',
  'rail-track laying and maintenance equipment operator',
  'reinforcing iron and rebar worker',
  'roofer',
  'roustabouts, oil and gas',
  'septic tank servicers and sewer pipe cleaner',
  'sheet metal worker',
  'solar photovoltaic installer',
  'stonemason',
  'structural iron and steel worker',
  'supervisor of construction and extraction workers'
];

const educationalTrainingAndLibrary = [
  'agricultural science teacher, postsecondary',
  'architecture teacher, postsecondary',
  'archivist',
  'art, drama and music teacher, postsecondary',
  'audio-visual and multimedia collections specialist',
  'biological science teacher, postsecondary',
  'business teacher, postsecondary',
  'career/technical education teacher, middle school',
  'career/technical education teacher, secondary school',
  'communications teacher, postsecondary',
  'computer science teacher, postsecondary',
  'criminal justice and law enforcement teacher, postsecondary',
  'curator',
  'education and library science teacher, postsecondary',
  'elementary school teacher',
  'engineering teacher, postsecondary',
  'farm and home management advisor',
  'forestry and conservation science teacher, postsecondary',
  'graduate teaching assistant',
  'grammar school teacher',
  'health teacher, postsecondary',
  'history teacher, postsecondary',
  'home economics teacher, postsecondary',
  'instructional coordinator',
  'language and literature teacher, postsecondary',
  'law teacher, postsecondary',
  'librarian',
  'library technician',
  'mathematical science teacher, postsecondary',
  'middle school teacher',
  'museum technician and conservator',
  'philosophy and religion teacher, postsecondary',
  'physical science teacher, postsecondary',
  'preschool and kindergarden teacher',
  'recreation and fitness studies teacher, postsecondary',
  'secondary school teacher',
  'social sciences teacher, postsecondary',
  'social work teacher, postsecondary',
  'special education teacher',
  'teacher assistant',
  'vocational education teacher, postsecondary'
];

const farmingForestryAndFishing = [
  'agricultural inspector',
  'agricultural worker',
  'animal breeder',
  'fisher and fishing worker',
  'forest and conservation worker',
  'graders and sorters, agricultural products',
  'hunter and trapper',
  'logging worker',
  'shepherd'
];

const foodPreparationAndServing = [
  'bartender',
  'chef and head cook',
  'cook',
  'dining room and cafeteria attendant',
  'dishwasher',
  'fast food and counter worker',
  'food preparation worker',
  'host and hostesses',
  'waiter and waitress'
];

const healthcare = [
  'anesthesiologist',
  'audiologist',
  'cardiovascular technologist and technician',
  'chiropractor',
  'dental assistant',
  'dental hygienist',
  'dentist',
  'diagnostical medical sonographer',
  'dietitian and nutritionist',
  'emergency medical technician and paramedic',
  'exercise physiologist',
  'family and general practitioner',
  'internist',
  'magnetic resonance imaging technologist',
  'massage therapist',
  'medical and clinical laboratory technician',
  'medical assistant',
  'medical equipment preparers',
  'medical records and health information technician',
  'nuclear medicine technologist',
  'nurse',
  'nursing assistant',
  'obstetrician and gynecologist',
  'occupational therapist',
  'ophthalmic medical technician',
  'optician',
  'optometric',
  'oral and maxillofacial surgeon',
  'orthodontist',
  'pediatrician',
  'pharmacist',
  'pharmacy aid',
  'pharmacy technician',
  'physical therapist',
  'physician assistant',
  'podiatrist',
  'psychiatric technician',
  'psychiatrist',
  'radiation therapist',
  'radiologic technologist',
  'recreational therapist',
  'respiratory therapist',
  'respiratory therapy technician',
  'speech-language pathologist',
  'surgeon',
  'surgical technologist',
  'veterinarian',
  'veterinary technologist and technician'
];

const installationMaintenanceAndRepair = [
  'aircraft mechanics and service technician',
  'automotive body and related repairer',
  'automotive glass installer and repairer',
  'automotive service technician and mechanic',
  'avionics technician',
  'bicycle repairer',
  'bus and truck mechanic',
  'camera and photographic equipment repairer',
  'coin, vending and amusement machine servicer and repairer',
  'commercial diver',
  'computer and office machine repairer',
  'control and valve installer and repairer',
  'diesel engine specialist',
  'electric motor and power tool repairer',
  'electrical and electronics installer and repairer',
  'electrical power line installer and repairer',
  'farm equipment mechanic and service technician',
  'first-line supervisor of mechanics, installers and repairers',
  'heating, air conditioning and refrigerator mechanic',
  'home appliance repairer',
  'industrial machinery mechanic',
  'maintenance worker',
  'medical equipment repairer',
  'millwright',
  'mobile heavy equipment mechanic',
  'motorboat mechanic and service technician',
  'motorcycle mechanic',
  'musical instrument repairer and tuner',
  'radio, cellular and tower equipment installer and repairer',
  'rail car repairer',
  'recreational vehicle service technician',
  'rigger',
  'telecommunication line installer and repairer',
  'telecommunications equipment installer and repairer',
  'tire repairer and changer',
  'watch repairer',
  'wind turbine service technician'
];

const legalOccupation = [
  'administrative law judges, adjudicators and hearing officer',
  'arbitrator, mediator and conciliator',
  'court reporter',
  'judge, magistrate judge and magistrate',
  'judicial law clerk',
  'lawyer',
  'legal support worker',
  'paralegal and legal assistant'
];

const lifePhysicalAndSocialScience = [
  'agricultural and food science technician',
  'animal scientist',
  'anthropologist',
  'archeologist',
  'astronomer',
  'atmospheric and space scientist',
  'biochemist and biophysicist',
  'biological technician',
  'chemical technician',
  'chemist',
  'clinical, counseling and school psychologist',
  'conservation scientist',
  'economist',
  'environmental scientist and specialist',
  'food scientist and technologist',
  'forensic science technician',
  'forest and conservation technician',
  'forester',
  'geographer',
  'geological and petroleum technician',
  'geoscientist',
  'health scientist',
  'historian',
  'hydrologist',
  'industrial-organizational psychologist',
  'material scientist',
  'medical scientist',
  'microbiologist',
  'nuclear technician',
  'physicist',
  'political scientist',
  'social science research assistant',
  'sociologist',
  'soil and plant scientist',
  'survey researcher',
  'urban and regional planner',
  'zoologist and wildlife biologist'
];

const management = [
  'administrative services manager',
  'advertising and promotions manager',
  'architectural and engineering manager',
  'branch manager',
  'brand manager',
  'business administration manager',
  'chairman of the supervisory board',
  'chief executive officer',
  'chief financial officer',
  'chief information officer',
  'compensation and benefit manager',
  'computer and information systems manager',
  'construction manager',
  'educational administrator',
  'emergency management director',
  'farmer, rancher and agricultural manager',
  'financial manager',
  'food service manager',
  'funeral service manager',
  'general and operations manager',
  'human resources manager',
  'industrial production manager',
  'lodging manager',
  'marketing manager',
  'medical and health service manager',
  'natural science manager',
  'postmaster and mail superintendent',
  'property, real estate and community association manager',
  'public relations and fund raising manager',
  'purchasing manager',
  'sales manager',
  'social and community service manager',
  'training and development manager',
  'transportation, storage and distribution manager'
];

const militarySpecificOccupation = [
  'air crew member',
  'air crew officer',
  'aircraft launch and recovery officer',
  'aircraft launch and recovery specialist',
  'armored assault vehicle crew member',
  'armored assault vehicle officer',
  'artillery and missile crew member',
  'artillery and missile officer',
  'command and control center officer',
  'command and control center specialist',
  'infantry',
  'infantry officer',
  'radar and sonar technician',
  'special forces',
  'special forces officer'
];

const officeAndAdministrativeSupport = [
  'bill and account collector',
  'billing and posting clerk',
  'bookkeeping, accounting and auditing clerk',
  'brokerage clerk',
  'cargo and freight agent',
  'computer operator',
  'correspondence clerk',
  'courier and messenger',
  'court, municipal and license clerk',
  'credit authorizer, checker and clerk',
  'customer service representative',
  'desktop publisher',
  'dispatcher',
  'executive administrative assistant',
  'executive secretary',
  'file clerk',
  'hotel, motel and resort desk clerk',
  'human resources assistant',
  'insurance claims and policy processing clerk',
  'legal secretary',
  'library assistant',
  'loan interviewer and clerk',
  'medical secretary',
  'meter reader',
  'order clerk',
  'payroll and timekeeping clerk',
  'postal service worker',
  'procurement clerk',
  'production, planning and expediting clerk',
  'receptionist and information clerk',
  'reservation and transportation tickets agent',
  'shipping, receiving and traffic clerk',
  'stock clerk and order filler',
  'switchboard operator',
  'teller',
  'travel clerk'
];

const personalCareAndService = [
  'animal trainer',
  'baggage porter',
  'barber',
  'childcare worker',
  'concierge',
  'first-line supervisor of personal service worker',
  'funeral service worker',
  'gaming service worker',
  'gaming supervisor ',
  'hairdresser, hairstylist and cosmetologist',
  'makeup artist',
  'manicurist and pedicurist',
  'nonfarm animal caretaker',
  'motion picture projectionist',
  'personal care aid',
  'recreational and fitness worker',
  'skincare specialist',
  'tour and travel guide',
  'usher, lobby attendant and ticket taker'
];

const productionOccupation = [
  'aircraft structure, surfaces, rigging and systems assembler',
  'baker',
  'butcher',
  'cabinetmaker and bench carpenter',
  'chemical plant and system operator',
  'chemical processing machine operator',
  'computer control programmer and operator',
  'electrical, electronics and electromechanical assembler',
  'engine assembler',
  'fiberglass laminator and fabricator',
  'first-line supervisor of production worker',
  'food and tobacco roasting, baking and drying machine operator',
  'forming machine setter',
  'furniture finisher',
  'gas plant operator',
  'heat treating equipment setter',
  'jewelers and precious stone and metal worker',
  'laundry and dry-cleaning worker',
  'layout worker',
  'machine tool cutting setter',
  'machinist',
  'metal furnace operator',
  'model maker',
  'molder and molding machine setter and operator',
  'plating and coating machine setter',
  'power plant operator',
  'printing worker',
  'sawing machine setter and operator',
  'semiconductor processor',
  'sewing machine operator',
  'shoe and leather worker',
  'stationary engineer',
  'structural metal fabricator and fitter',
  'tailor and dressmaker',
  'textile machine setter and operator',
  'textile, garment and related materials presser',
  'tool and die maker',
  'tool grinder',
  'water and wastewater treatment plant operator',
  'welding, soldering and brazing worker'
];

const protectiveService = [
  'animal control worker',
  'bailiff',
  'correctional officer and jailer',
  'detective and criminal investigator',
  'fire inspector and investigator',
  'firefighter',
  'first-line supervisors of protective service workers',
  'fish and game warden',
  'lifeguard',
  'ski-patrol and other recreational protective service',
  'police officer',
  'private detective and investigator',
  'security guard',
  'transportation security screener'
];

const salesAndRelatedOccupation = [
  'advertising sales agent',
  'cashier',
  'counter and rental clerk',
  'demonstrator and product promoter',
  'first-line supervisor of sales worker',
  'florist',
  'insurance sales agent',
  'model',
  'parts salesperson',
  'real estate broker',
  'real estate sales agent',
  'retail salesperson',
  'sales engineer',
  'sales representative',
  'securities, commodities and financial service sales agent',
  'telesales worker',
  'travel agent'
];

const transportationAndMaterialMoving = [
  'air traffic controller',
  'aircraft cargo handling supervisor',
  'airfield operations specialist',
  'ambulance driver',
  'bridge and lock tender',
  'bus driver',
  'captains, mates or pilot of water vessel',
  'chauffeur',
  'cleaner of vehicle and equipment',
  'conveyor operator',
  'crane and tower operator',
  'dredge operator',
  'first-line supervisor of transportation worker',
  'flight attendant',
  'flight engineer',
  'gas compressor and gas pumping station operator',
  'heavy and tractor-trailer truck driver',
  'hoist and winch operator',
  'industrial truck and tractor operator',
  'light truck or delivery service driver',
  'loading machine operator',
  'locomotive engineer',
  'mine shuttle car operator',
  'packer and packager',
  'parking lot attendant',
  'pilot',
  'rail transportation worker',
  'railroad brake, signal and switch operator',
  'railroad conductor and yardmaster',
  'refuse and recyclable material collector',
  'sailor and marine oiler',
  'ship engineer',
  'subway and streetcar operator',
  'tank car, truck and ship loader',
  'taxi driver',
  'traffic technician',
  'transportation inspector'
];

const currentlyInSchoolUniversityVocationalTraining = [
  'student',
  'apprentice / trainee',
  'student trainee',
  'doctoral / phd student',
  'student teacher'
];

const occupations = [
  ...architectureAndEngineering,
  ...artsDesignEntertainmentSportAndMedia,
  ...buildingGroundsCleaningAndMaintenance,
  ...businessAndFinancialOperations,
  ...communityAndSocialService,
  ...computerAndMathematicalOperations,
  ...constructionAndExtractionOperations,
  ...educationalTrainingAndLibrary,
  ...farmingForestryAndFishing,
  ...foodPreparationAndServing,
  ...healthcare,
  ...installationMaintenanceAndRepair,
  ...legalOccupation,
  ...lifePhysicalAndSocialScience,
  ...management,
  ...militarySpecificOccupation,
  ...officeAndAdministrativeSupport,
  ...personalCareAndService,
  ...productionOccupation,
  ...protectiveService,
  ...salesAndRelatedOccupation,
  ...transportationAndMaterialMoving,
  ...currentlyInSchoolUniversityVocationalTraining
];

module.exports = occupations;
