
export const foods = [
  'afghani',
  'african',
  'albanian',
  'american',
  'arab',
  'argentinean',
  'armenian',
  'asian',
  'australian',
  'austrian',
  'azerbaijani',
  'bahamian',
  'balkan',
  'balti',
  'bangladeshi',
  'bar',
  'barbecue',
  'belgian',
  'brazilian',
  'brew pub',
  'british',
  'bon vivant',
  'bulgarian',
  'burmese',
  'cajun & creole',
  'cambodian',
  'canadian',
  'carribean',
  'caucasian',
  'central-american',
  'central-asian',
  'central-european',
  'chilean',
  'chinese',
  'colombian',
  'contemporary',
  'costa rican',
  'croatian',
  'cuban',
  'czech',
  'danish',
  'delicatessen',
  'diner',
  'dutch',
  'eastern european',
  'ecuadorean',
  'egyptian',
  'ethiopian',
  'european',
  'fast food',
  'filipino',
  'french',
  'fujian',
  'fusion',
  'gastropub',
  'georgian',
  'german',
  'gluten free',
  'gourmet',
  'greek',
  'guatemalan',
  'halal',
  'hawaiian',
  'hungarian',
  'indian',
  'indonesian',
  'international',
  'irish',
  'israeli',
  'italian',
  'jamaican',
  'japanese',
  'korean',
  'kosher',
  'kurdish',
  'latin',
  'latvian',
  'lebanese',
  'louisiana creole',
  'malaysian',
  'mediterranean',
  'mexican',
  'middle eastern',
  'mongolian',
  'maroccan',
  'native american',
  'nepali',
  'new zealand',
  'norwegian',
  'pacific rim',
  'pakistani',
  'pashtun',
  'persian',
  'peruvian',
  'pizza',
  'plain fare',
  'polish',
  'polynesian',
  'portuguese',
  'pub',
  'punjabi',
  'puerto rican',
  'romanian',
  'russian',
  'salvadoran',
  'scandinavian',
  'scottish',
  'seafood',
  'singaporean',
  'slovenian',
  'soul food',
  'soups',
  'south american',
  'southwestern',
  'spanish',
  'sri lankan',
  'steakhouse',
  'street food',
  'sushi',
  'swedish',
  'swiss',
  'taiwanese',
  'tartar',
  'thai',
  'tibetan',
  'tunesian',
  'turkish',
  'ukrainian',
  'uzbek',
  'vegan',
  'vegetarian',
  'venezuelan',
  'vietnamese',
  'welsh',
  'wine bar',
  'xinjiang',
  'yamal',
  'yunnan',
];
